### ISSUE TITLE
Gowalla dataset does not provide

### ISSUE THREAD

**Issue by ruiwenfan** [icmpnorequest/DASFAA2023_MSTHN#1]
Thanks a lot for the code provided , I really appreciate your excellent work. But I found that the gowalla dataset is not provided, could you please give it or a preprocessing method for the dataset？

**Comment by icmpnorequest** [comment]
> 

Hi ruiwen, 
Thanks for watching our work. The Gowalla dataset is too large to upload and we attach the link we refer. The preprocessing procedure is described in the Experiment section in the paper, and it is the same as LSTPM (2020-AAAI) do.
Maybe you could try with package `Pandas` to preprocess it. Hope it would help.

**Comment by weichaoliam** [comment]
Hello, have you successfully processed the Gowalla dataset through the method provided by the author?Hope to get your reply, I may need your help

**Comment by weichaoliam** [comment]
> Thanks a lot for the code provided , I really appreciate your excellent work. But I found that the gowalla dataset is not provided, could you please give it or a preprocessing method for the dataset？
Hello, have you successfully processed the Gowalla dataset through the method provided by the author?Hope to get your reply, I may need your help

**Comment by LinkaSage** [comment]
> Thanks a lot for the code provided , I really appreciate your excellent work. But I found that the gowalla dataset is not provided, could you please give it or a preprocessing method for the dataset？

Hello, have you successfully processed the Gowalla dataset through the method provided by the author?Hope to get your reply, I may need your help
