### ISSUE TITLE
作者您好，数据集部分有一些问题呢。

### ISSUE THREAD

**Issue by ckq11903** [icmpnorequest/DASFAA2023_MSTHN#2]
train和test文件打开是乱码的，请问怎么解决呢

**Comment by icmpnorequest** [comment]
> train和test文件打开是乱码的，请问怎么解决呢

Hi @ckq11903 ,
We have saved pickle object into a txt file, so please use `pickle.load(txt_file)` to load the dataset. You could refer to our codes [def load_list_with_pkl(filename)](https://github.com/icmpnorequest/DASFAA2023_MSTHN/blob/0f8d8ec570e4467552806595986ba1e67ab1211b/utils.py#L67) in `utils.py`. 
Hope it would help.

**Comment by ckq11903** [comment]
> > train和test文件打开是乱码的，请问怎么解决呢
> 
> Hi @ckq11903 , 你好， We have saved pickle object into a txt file, so please use `pickle.load(txt_file)` to load the dataset. You could refer to our codes [def load_list_with_pkl(filename)](https://github.com/icmpnorequest/DASFAA2023_MSTHN/blob/0f8d8ec570e4467552806595986ba1e67ab1211b/utils.py#L67) in `utils.py`. 我们已经将pickle对象保存到一个txt文件中，所以请使用 `pickle.load(txt_file)` 加载数据集。你可以参考我们的代码def load_list_with_pkl（filename）在 `utils.py` 。 Hope it would help. 希望能帮上忙。

感谢作者，可以了。非常感谢您。

**Comment by icmpnorequest** [comment]
> > > train和test文件打开是乱码的，请问怎么解决呢
> > 
> > 
> > Hi @ckq11903 , 你好， We have saved pickle object into a txt file, so please use `pickle.load(txt_file)` to load the dataset. You could refer to our codes [def load_list_with_pkl(filename)](https://github.com/icmpnorequest/DASFAA2023_MSTHN/blob/0f8d8ec570e4467552806595986ba1e67ab1211b/utils.py#L67) in `utils.py`. 我们已经将pickle对象保存到一个txt文件中，所以请使用 `pickle.load(txt_file)` 加载数据集。你可以参考我们的代码def load_list_with_pkl（filename）在 `utils.py` 。 Hope it would help. 希望能帮上忙。
> 
> 感谢作者，可以了。非常感谢您。

@ckq11903 Glad it helps. I will close this issue.

**Comment by ckq11903** [comment]
![image](https://github.com/icmpnorequest/DASFAA2023_MSTHN/assets/48143334/951c6677-d8aa-4c8f-83b1-16aaf41e2c76)
作者您好，打扰了，在读取NYC的test文件报错，TKY文件是没有问题的。

**Comment by icmpnorequest** [comment]
> ![image](https://user-images.githubusercontent.com/48143334/268640886-951c6677-d8aa-4c8f-83b1-16aaf41e2c76.png) 作者您好，打扰了，在读取NYC的test文件报错，TKY文件是没有问题的。

Hi @ckq11903 ,
It works fine on macOS and Linux. Maybe you could set the encoding type as utf-8. Please refer to our provided codes to load data from dataset.py.

**Comment by ckq11903** [comment]
感谢作者，在windows用pycharm加载数据不太行，没事，我先用TKY去理解您论文的逻辑。我目前有一个小问题，就是您构建图和超图的方式我不太理解，因为我平常都是基于DGL和PYG的框架下去构建图的，请问您有什么提供的资料参考您构建的图吗？

**Comment by icmpnorequest** [comment]
Hi @ckq11903 
Please refer to our paper for construction of hypergraph and the codes are easy to follow with provided `README`. DGL and PyG are two widely used tool for GNN, but only PyG supports limited content of hypergraph. Thus, we build our codes with PyTorch, including hypergraph construction and hypergraph neural networks. Furthermore, we should communicate on Github in English.
